[package]
name = "cesrox"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
cesride = { path = "/Users/artem/cesride" }
parside = { path = "/Users/artem/parside" }
thiserror = "1.0"